spring:
  application:
    name: authentication-service
  config:
    import: "optional:configserver:http://localhost:8088"
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 2
auth:
  jwt:
    hmacKey: 'secret'