spring:
  application:
    name: authentication-service
  config:
    import: "optional:configserver:http://localhost:8088"
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis

auth:
  jwt:
    hmacKey: 'secret'