spring:
  application:
    name: authentication-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_security
    username: postgres
    password: 3275
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    service-url:
      defaultZone : http://user:password@localhost:8761/eureka

server:
  port: 8081

auth:
  basic:
    username: 'danis0n'
    password: 'password'
  jwt:
    hmacKey: 'secret'