spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: 3275
#    jpa:
#      hibernate:
#        ddl-auto: update

#eureka:
#  client:
#    service-url:
#      defaultZone : http://user:password@localhost:8761/eureka

#server:
#  port: 0