CREATE TABLE app_admin (
    uuid UUID NOT NULL UNIQUE PRIMARY KEY,
    username VARCHAR(32) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE app_user (
    uuid UUID NOT NULL UNIQUE PRIMARY KEY,
    username VARCHAR(32) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(50) UNIQUE
);